esphome:
  name: fauxmo-bridge-demo
  platformio_options:
    build_flags:
      -DDEBUG_FAUXMO=Serial
      -DDEBUG_FAUXMO_VERBOSE_TCP=true
      -DDEBUG_FAUXMO_VERBOSE_UDP=true

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
api:
ota:
 - platform: esphome
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Pull our external component from a local folder
external_components:
  - source:
      type: local
      path: mods/fauxmo_bridge/components

# Your real ESPHome lights as usual
light:
  - platform: monochromatic
    name: Desk Light
    id: desk_light
    output: pwm1
    internal: true
    gamma_correct: 1.0
    #default_transition_length: 0s
    

output:
  - platform: ledc
    id: pwm1
    inverted: true
    pin: 8

# ← NEW: proper external component usage (no custom_component)
fauxmo_bridge:
  mdns_name: esp-hue
  tcp_port: 80
  #outputs:
  #  - name: Desk
  #  - output_id: pwm1
  lights:
    - name: Desk
      light_id: desk_light

